### ISSUE TITLE
[REFACTORING](Entity) 엔티티 롬복 수정

### ISSUE THREAD

**Issue by Subak-Uncle** [MTVS-third-study/adregamdi#135]
## Description
Entity에 @NoArgsConstructor(access = AccessLevel.PROTECTED) 롬복 수정

## TODO
- [x]  장소 엔티티 수정
- [x] 카테고리 엔티티 수정
- [x] 태그 엔티티 수정
- [x] 도시 엔티티 수정
- [x] 동 엔티티 수정
- [x] 장소태그 엔티티 수정

## ETC
* 기타사항을 작성한다.
