### ISSUE TITLE
[REFACTORING](일정) 창 변화 메소드 제작

### ISSUE THREAD

**Issue by Subak-Uncle** [MTVS-third-study/adregamdi#195]
## Description
일정 페이지는 한 페이지를 css로 구현하다보니 많은 이벤트가 발생합니다. 그러므로 창 변환 메소드가 필요함.

## TODO
- [x] 일정 창 보여주기 메소드
- [x] 검색 창  보여주기 메소드
- [x] 상세 정보 창 보여주기 메소드
- [ ] 리뷰 창 보여주기 메소드

## ETC
* 기타사항을 작성한다.
